### ISSUE TITLE
加载插件报错

### ISSUE THREAD

**Issue by fsqhn** [ldcivan/Yunzai_imgSearcher#1]
加载插件后提示如下：

yunzai-bot    | [YzBot][16:09:51.031][MARK] [修改插件][example][Yunzai_imgSearcher.js]
yunzai-bot    | [YzBot][16:09:51.048][ERRO] 载入插件错误：example/Yunzai_imgSearcher.js
yunzai-bot    | [YzBot][16:09:51.048][ERRO] Error [ERR_REQUIRE_ESM]: require() of ES Module /app/Yunzai-Bot/node_modules/_axios@1.2.1@axios/index.js from /app/Yunzai-Bot/plugins/example/Yunzai_imgSearcher.js not supported.
yunzai-bot    | Instead change the require of index.js in /app/Yunzai-Bot/plugins/example/Yunzai_imgSearcher.js to a dynamic import() which is available in all CommonJS modules.
yunzai-bot    |     at file:///app/Yunzai-Bot/plugins/example/Yunzai_imgSearcher.js?1672214991031:6:15
yunzai-bot    | [YzBot][16:09:51.500][MARK] [新增插件][example][Yunzai_imgSearcher.js]
yunzai-bot    | [YzBot][16:09:51.510][ERRO] 载入插件错误：example/Yunzai_imgSearcher.js
yunzai-bot    | [YzBot][16:09:51.511][ERRO] Error [ERR_REQUIRE_ESM]: require() of ES Module /app/Yunzai-Bot/node_modules/_axios@1.2.1@axios/index.js from /app/Yunzai-Bot/plugins/example/Yunzai_imgSearcher.js not supported.
yunzai-bot    | Instead change the require of index.js in /app/Yunzai-Bot/plugins/example/Yunzai_imgSearcher.js to a dynamic import() which is available in all CommonJS modules.
yunzai-bot    |     at file:///app/Yunzai-Bot/plugins/example/Yunzai_imgSearcher.js?1672214991:6:15

我是用docker部署的云仔，docker内部没cnpm的，我直接进到容器内用npm装了个cnpm，再运行的cnpm install axios，最后才复制的js文件。应该不影响？
js插件内的SAUCENAO_API_KEY我是已经修改了的。

**Comment by YujioNako** [comment]
docker我不是很了解，他好多路径是不一样的23333 个人感觉你云崽本体是正常的理论上require那里不会出错才对

你先更新一下到我最新发布的那个js

然后我想了几个解决方法：1.不要用cnpm了，用npm安装就好；2.不知道您是在哪个目录npm安装的，确认一下安装的目录有个叫node_module的文件夹；

**Comment by yiyule10** [comment]
V3版本在yunzai根目录
<code>pnpm add axios -w</code>

**Comment by shuaji233** [comment]
插件报错403
[pic_search][pic_search]
[YzBot][22:03:42.108][ERRO] AxiosError: Request failed with status code 403
    at settle (/root/node_modules/axios/dist/node/axios.cjs:1855:12)
    at Unzip.handleStreamEnd (/root/node_modules/axios/dist/node/axios.cjs:2712:11)
    at Unzip.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by fsqhn** [comment]
脑壳疼，在docker内的yunzai根目录跑了一趟npm install ``axios，然后一堆报错，又跑了一趟上面大佬说的`pnpm add axios -w`

接着还是报错。
yunzai-bot    | [YzBot][22:15:28.523][MARK] [新增插件][example][Yunzai_imgSearcher.js]
yunzai-bot    | [YzBot][22:15:28.527][ERRO] 载入插件错误：example/Yunzai_imgSearcher.js
yunzai-bot    | [YzBot][22:15:28.527][ERRO] Error [ERR_REQUIRE_ESM]: require() of ES Module /app/Yunzai-Bot/node_modules/_axios@1.2.1@axios/index.js from /app/Yunzai-Bot/plugins/example/Yunzai_imgSearcher.js not supported.
yunzai-bot    | Instead change the require of index.js in /app/Yunzai-Bot/plugins/example/Yunzai_imgSearcher.js to a dynamic import() which is available in all CommonJS modules.
yunzai-bot    |     at file:///app/Yunzai-Bot/plugins/example/Yunzai_imgSearcher.js?1672236928:6:15

问题是我一路cd进去，是有/app/Yunzai-Bot/node_modules/_axios@1.2.1@axios/index.js这个文件的。

**Comment by yiyule10** [comment]
> 脑壳疼，在docker内的yunzai根目录跑了一趟npm install ``axios，然后一堆报错，又跑了一趟上面大佬说的`pnpm add axios -w`
> 
> 接着还是报错。 yunzai-bot | [YzBot][22:15:28.523][MARK] [新增插件][example][Yunzai_imgSearcher.js] yunzai-bot | [YzBot][22:15:28.527][ERRO] 载入插件错误：example/Yunzai_imgSearcher.js yunzai-bot | [YzBot][22:15:28.527][ERRO] Error [ERR_REQUIRE_ESM]: require() of ES Module /app/Yunzai-Bot/node_modules/_axios@1.2.1@axios/index.js from /app/Yunzai-Bot/plugins/example/Yunzai_imgSearcher.js not supported. yunzai-bot | Instead change the require of index.js in /app/Yunzai-Bot/plugins/example/Yunzai_imgSearcher.js to a dynamic import() which is available in all CommonJS modules. yunzai-bot | at file:///app/Yunzai-Bot/plugins/example/Yunzai_imgSearcher.js?1672236928:6:15
> 
> 问题是我一路cd进去，是有/app/Yunzai-Bot/node_modules/_axios@1.2.1@axios/index.js这个文件的。

重启一下机器人

**Comment by fsqhn** [comment]
太强了，成功跑起来了。群聊试了下可以。
不过好像目前企鹅把p站标了叹号，然后私聊里叹号链接+图片会直接风控发不出来？

**Comment by YujioNako** [comment]
> 插件报错403
> [pic_search][pic_search]
> [YzBot][22:03:42.108][ERRO] AxiosError: Request failed with status code 403
> at settle (/root/node_modules/axios/dist/node/axios.cjs:1855:12)
> at Unzip.handleStreamEnd (/root/node_modules/axios/dist/node/axios.cjs:2712:11)
> at Unzip.emit (node:events:539:35)
> at endReadableNT (node:internal/streams/readable:1345:12)
> at processTicksAndRejections (node:internal/process/task_queues:83:21)

403是forbidden的状态码呀，你这大概率是被api控制用量了，可以选择换个apikey或者等一段时间再试试

**Comment by YujioNako** [comment]
> 太强了，成功跑起来了。群聊试了下可以。
> 不过好像目前企鹅把p站标了叹号，然后私聊里叹号链接+图片会直接风控发不出来？

我估计可能是我没写好，导致私聊发不出来23333

我明天试着改改吧
