### ISSUE TITLE
插件报错求解答

### ISSUE THREAD

**Issue by CICILC** [ldcivan/Yunzai_imgSearcher#2]
大佬这个报错是什么原因导致的呀 我用的pnpm add axios -w安装的
![-6ee975a97e77fd28](https://user-images.githubusercontent.com/115946224/210268346-6610e5cd-8ad2-4a9a-a34d-550b14ad45af.jpg)

**Comment by YujioNako** [comment]
ECONNRESET的话估计是API的锅……这个错误是一直在报嘛？还是说间隔出现？

另，报错内容是只有上面这些吗，我总感觉还缺了点23333

**Comment by CICILC** [comment]
只要搜索就会报错 无论是群还是私聊

目前确实只有这么点 但之前报错是搜索结果123read RECONNRESET然后才报错（记录久远找不到了）也有可能是axios没有正确安装导致的

**Comment by YujioNako** [comment]
有没有试试npm或者cnpm安装？就是按照你当时装yunzai依赖的时候那样子来

如果也不行的话我也没辙了，因为在我这边没法复现问题2333

**Comment by YujioNako** [comment]
> 只要搜索就会报错 无论是群还是私聊
> 
> 目前确实只有这么点 但之前报错是搜索结果123read RECONNRESET然后才报错（记录久远找不到了）也有可能是axios没有正确安装导致的

我改了一下，不再需要axios了，更新一下插件再试试吧
