### ISSUE TITLE
搜图报错

### ISSUE THREAD

**Issue by friends-xiaohuli** [ldcivan/Yunzai_imgSearcher#3]
![图片](https://user-images.githubusercontent.com/101490945/210488421-a9737fc2-c7ab-4c3b-b3d9-efb9fb213862.png)
就很迷惑，大佬求解，没装依赖，换过秘钥

**Comment by YujioNako** [comment]
尝试一下pnpm add -g node-fetch 

不行的话cnpm install node-fetch 或者 npm install node-fetch

还不行的话我就没辙了

**Comment by friends-xiaohuli** [comment]
![图片](https://user-images.githubusercontent.com/101490945/210540924-4932ad82-7374-4709-9dd5-f0ff399c0324.png)
还是这样，3个命令都试过了

**Comment by YujioNako** [comment]
> ![图片](https://user-images.githubusercontent.com/101490945/210540924-4932ad82-7374-4709-9dd5-f0ff399c0324.png) 还是这样，3个命令都试过了

你pnpm没add上模块，你得先pnpm setup再add；或者直接pnpm add node-fetch不全局安装也行

**Comment by friends-xiaohuli** [comment]
![图片](https://user-images.githubusercontent.com/101490945/210547064-2f7c224d-8b0c-45dd-838a-37dd808e3a24.png)
？难道是输命令的目录不对

**Comment by YujioNako** [comment]
emmm

去查查百度吧，这个超出我的能力范围了2333

**Comment by CICILC** [comment]
我先运行了pnpm add node-fetch -w
再运行pnpm add -g node-fetch
都提示安装上fetch了但是仍然在使用的时候提示fetch is not defined
![-76c8d5723bb609e7](https://user-images.githubusercontent.com/115946224/210833804-70bfcfa4-75fd-4de5-b5f4-979055108bf2.jpg)

**Comment by YujioNako** [comment]
> 我先运行了pnpm add node-fetch -w 再运行pnpm add -g node-fetch 都提示安装上fetch了但是仍然在使用的时候提示fetch is not defined ![-76c8d5723bb609e7](https://user-images.githubusercontent.com/115946224/210833804-70bfcfa4-75fd-4de5-b5f4-979055108bf2.jpg)

那你在三个import下面再添一行<code>import fetch from "node-fetch"</code>吧
