### ISSUE TITLE
大佬求解

### ISSUE THREAD

**Issue by Mokuei** [ldcivan/Yunzai_imgSearcher#4]
大佬求解，请问搜图报错这个怎么解决![Screenshot_20230114-233111_(1).png](https://user-images.githubusercontent.com/112179934/212480718-b92c6a14-3ad9-44d5-b0c1-265afea2bc3f.png)

**Comment by YujioNako** [comment]
你ping一下saucenao看看能不能通，这个看起来是bot和服务器通信的问题而不是bot本身的问题

**Comment by Mokuei** [comment]
> 你ping一下saucenao看看能不能通，这个看起来是bot和服务器通信的问题而不是bot本身的问题

大佬我运行ping https://saucenao.com/后是未知的名称或服务，运行ping https://saucenao.com/ -t后是这样![Screenshot_20230115-160800_(1).png](https://user-images.githubusercontent.com/112179934/212529889-d0e3c0f5-3c61-40c5-ad86-3df2181782b3.png)

**Comment by YujioNako** [comment]
怀疑是你的网络配置有点问题，可以参考一下：https://blog.csdn.net/w598882992/article/details/127282293

这个问题我没出过，所以我也没法提出自己的建议23333

**Comment by Mokuei** [comment]
> 怀疑是你的网络配置有点问题，可以参考一下：https://blog.csdn.net/w598882992/article/details/127282293
> 
> 这个问题我没出过，所以我也没法提出自己的建议23333

大佬，我试着重新ping一下，发现网站前面是https://就会出现未知的名称会服务（https://www.baidu.com也是一样  ），而我直接ping www.saucenao.com居然不提示了      ![Screenshot_20230115-214936_(1).png](https://user-images.githubusercontent.com/112179934/212545352-5d71143c-89e5-4363-a854-417393906deb.png)

**Comment by baizhili0** [comment]
> > 怀疑是你的网络配置有点问题，可以参考一下：https://blog.csdn.net/w598882992/article/details/127282293
> > 
> > 这个问题我没出过，所以我也没法提出自己的建议23333
> 
> 大佬，我试着重新ping一下，发现网站前面是https://就会出现未知的名称会服务（https://www.baidu.com也是一样  ），而我直接ping www.saucenao.com居然不提示了      ![Screenshot_20230115-214936_(1).png](https://user-images.githubusercontent.com/112179934/212545393-c4b1cd44-2095-4977-a1af-298c71bcfb01.png)

**Comment by YujioNako** [comment]
> 
所以现在还是报错吗，还报错我真没办法了23333

**Comment by Mokuei** [comment]
> > 
> 所以现在还是报错吗，还报错我真没办法了23333
> 

试了好久好多方法还是报错，已经摆烂没搞了

**Comment by yingmuluoshuang** [comment]
我也一样，不过我挂上梯子就解决了

**Comment by YujioNako** [comment]
放弃解决
