### ISSUE TITLE
搜图报报错，TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by JY69** [ldcivan/Yunzai_imgSearcher#5]
![QQ图片20230126114133](https://user-images.githubusercontent.com/123614017/214754134-f2677a7f-b5c7-4b50-bbf7-772edd417a89.png)

请问大佬，这个报错怎么弄？

**Comment by YujioNako** [comment]
> ![QQ图片20230126114133](https://user-images.githubusercontent.com/123614017/214754134-f2677a7f-b5c7-4b50-bbf7-772edd417a89.png)
> 
> 
> 
> 请问大佬，这个报错怎么弄？

这大概是没获取到内容，怀疑是无法与api通信或者你的key被ban了；考虑给bot挂个梯子再试试或者去官网重置一下apikey吧
另，你是不是用了程序里自带的apikey，那个key是我测试时用的，可能早就失效了

**Comment by JY69** [comment]
key是自行注册的。按照大佬的思路检查了下，确实问题出在key上，当时操作把key重置了，没有更新在脚本上。现在可正常用了，谢谢大佬。
