### ISSUE TITLE
搜图出现，api改好了

### ISSUE THREAD

**Issue by ayachinenez** [ldcivan/Yunzai_imgSearcher#6]
搜图出现，api改好了，大佬出现了这个问题，求解！

[YzBot][15:46:25.594][ERRO] [pic_search][pic_search]
[YzBot][15:46:25.595][ERRO] TypeError: JSON.stringify(...).replaceAll is not a function
    at example.pic_search (file:///root/Yunzai-Bot/plugins/example/Yunzai_imgSearcher.js:106:94)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async PluginsLoader.deal (file:///root/Yunzai-Bot/lib/plugins/loader.js:251:52)

**Comment by YujioNako** [comment]
> 搜图出现，api改好了，大佬出现了这个问题，求解！
> 
> [YzBot][15:46:25.594][ERRO] [pic_search][pic_search] [YzBot][15:46:25.595][ERRO] TypeError: JSON.stringify(...).replaceAll is not a function at example.pic_search (file:///root/Yunzai-Bot/plugins/example/Yunzai_imgSearcher.js:106:94) at runMicrotasks () at processTicksAndRejections (internal/process/task_queues.js:93:5) at async PluginsLoader.deal (file:///root/Yunzai-Bot/lib/plugins/loader.js:251:52)

大概是api反信为空，检查apikey或ping一下api试试。如果已经解决了的话，能请问一下是怎么解决的吗，这对我们改进脚本很有必要!

**Comment by ayachinenez** [comment]
> > 搜图出现，api改好了，大佬出现了这个问题，求解！
> > [YzBot][15:46:25.594][厄罗][pic_search][pic_search][YzBot][15:46:25.595][厄罗]TypeError： JSON.stringify（...）.replaceAll 不是 example.pic_search （file:///root/Yunzai-Bot/plugins/example/Yunzai_imgSearcher.js:106:94） at runMicrotasks （） at processTicksAndRejections （internal/process/task_queues.js：93：5） at async PluginsLoader.deal （file:///root/Yunzai-Bot/lib/plugins/loader.js:251:52）
> 
> 大概是api反信为空，检查apikey或ping一下API试试。如果已经解决了的话，能请问一下是怎么解决的吗，这对我们改进脚本很有必要!

Node.js版本过低，没有JSON.stringify（...）.replaceAll 这个函数。我是14版本得，升了18就好了
